site_name: Catadelphia
nav:
    - Getting Started: index.md
    - Shelters & Clinics: shelters.md
    - Vets: vets.md
    - Trapping: trapping.md
    - Fostering: fostering.md
    - Adoptions: adopt.md
    - Issues: issues.md
    - Programs: programs.md
plugins:
    - search