site_name: Catadelphia
nav:
    - Home: index.md
    - Getting Started: start.md
    - Shelters & Clinics: shelters.md
    - Vets: vets.md
    - Trapping: trapping.md
    - Fostering: fostering.md
    - Adoptions: adopt.md
    - Medical Issues: medical.md
plugins:
    - search